services:
  openmeter:
    build:
      context: .
      dockerfile: Dockerfile
    command: openmeter
    environment:
      KAFKA_BROKERS: ${KAFKA_BROKERS}
      KAFKA_USERNAME: ${KAFKA_USERNAME}
      KAFKA_PASSWORD: ${KAFKA_PASSWORD}
      KAFKA_SECURITY_PROTOCOL: ${KAFKA_SECURITY_PROTOCOL}
      KAFKA_SASL_MECHANISM: ${KAFKA_SASL_MECHANISM}
      DATABASE_URL: ${DATABASE_URL} # Postgres or ClickHouse, depending on setup
      REDIS_URL: ${REDIS_URL}       # Optional: if using Redis for deduplication
      OPENMETER_TOKEN: ${OPENMETER_TOKEN} # Optional: for API auth
    ports:
      - "8080:8080"